language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test --all-features
  - cargo test --no-default-features
  - cargo test --no-default-features --features charsets
  - cargo test --no-default-features --features compress
  - cargo test --no-default-features --features json
  - cargo test --no-default-features --features tls

