language: rust
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - rustup component add rustfmt clippy

script:
  - cargo fmt -- --check
  - cargo clippy --all-features --all-targets -- --deny warnings
  - ./run-tests.sh
