[package]
name = "lynx"
version = "0.1.2"
authors = ["Simon Bernier St-Pierre <git@sbstp.ca>"]
edition = "2018"
license = "MPL-2.0"

readme = "README.md"
description = "Small and lightweight HTTP client"
documentation = "https://docs.rs/lynx"
homepage = "https://github.com/sbstp/lynx"
repository = "https://github.com/sbstp/lynx"
keywords = ["http", "client", "tls"]

[dependencies]
http = "0.1"
log = "0.4"
url = "1"
encoding_rs = { version = "0.8", optional = true }
libflate = { version = "0.1", optional = true }
native-tls = { version = "0.2", optional = true }

[dev-dependencies]
env_logger = "0.5"

[features]
compress = ["libflate"]
charsets = ["encoding_rs"]
tls = ["native-tls"]
default = ["compress", "charsets", "tls"]

[package.metadata.docs.rs]
all-features = true
