cargo-features = ["edition"]

[package]
name = "tinyhttp"
version = "0.1.0"
authors = ["Simon <git@sbstp.ca>"]
edition = "2018"

[dependencies]
encoding_rs = "0.8"
http = "0.1"
log = "0.4"
native-tls = "0.2.1"
url = "1"

[dev-dependencies]
env_logger = "0.5"

[profile.dev]
debug = false

[profile.release]
debug = false
lto = true
